import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Forumview.module.css'
import { Icon } from '@mui/material'
import AppBanner from '@/components/AppBanner';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
     <AppBanner />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div name="underbanner" className={styles.under_banner}>
          <div name="leftside" className={styles.left_side}>
            
          </div>
          <div name="comments_graphics" className={styles.comments}>
            <div name="comment outside container" className={styles.comment_outside_container}>
              <div id="comments" name="comment inside container" className={styles.comment_inside_container}>
                <div name="title" className={styles.title}>
                  <div>
                    <span>
                      Map of the United States
                    </span>
                  </div>
                  <span style={{fontSize:"1.2rem"}}>
                    Posted by: PizzaLover
                  </span>
                </div>
                <div className={styles.title}>
                  <span style={{fontSize:"1.2rem", fontWeight:"normal"}}>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
                    magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut 
                    labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor 
                    incididunt ut labore et dolore magna aliqua.
                  </span>
                </div>
                <br></br> <br></br>
                <hr size="10" noshade="noshade"></hr>
                <div name="create comment" className={styles.create_comment_container}>
                  <textarea placeholder="Comment?" name="create comment textbox" className={styles.comment_textbox}>
                  </textarea>
                  <button className={styles.submit_comment}>
                    Submit
                  </button>
                </div>
                <div name="comment container" className={styles.comments_container}>
                  <div name="comment" className={styles.comment_card}>
                    <div>
                      <span style={{fontWeight:"bold"}}>
                        PizzaHater
                      </span>
                    </div>
                    <div>
                      <span>
                      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure 
                      dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                      </span>
                    </div>
                  </div>
                  <div name="comment" className={styles.comment_card}>
                    <div>
                      <span style={{fontWeight:"bold"}}>
                        PizzaHater
                      </span>
                    </div>
                    <div>
                      <span>
                      Lorem ipsum dolor sit amet, consectetur
                      </span>
                    </div>
                  </div>
                  <div name="comment" className={styles.comment_card}>
                    <div>
                      <span style={{fontWeight:"bold"}}>
                        PizzaHater
                      </span>
                    </div>
                    <div>
                      <span>
                      Lorem ipsum dolor sit amet, consectetur
                      </span>
                    </div>
                  </div>
                  <div name="comment" className={styles.comment_card}>
                    <div>
                      <span style={{fontWeight:"bold"}}>
                        PizzaHater
                      </span>
                    </div>
                    <div>
                      <span>
                      Lorem ipsum dolor sit amet, consectetur
                      </span>
                    </div>
                  </div>
                  <div name="comment" className={styles.comment_card}>
                    <div>
                      <span style={{fontWeight:"bold"}}>
                        PizzaHater
                      </span>
                    </div>
                    <div>
                      <span>
                      Lorem ipsum dolor sit amet, consectetur
                      </span>
                    </div>
                  </div>
                  <div name="comment" className={styles.comment_card}>
                    <div>
                      <span style={{fontWeight:"bold"}}>
                        PizzaHater
                      </span>
                    </div>
                    <div>
                      <span>
                      Lorem ipsum dolor sit amet, consectetur
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
